require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WordListsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # WordList. As you add validations to WordList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WordListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all word_lists as @word_lists" do
      word_list = WordList.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:word_lists)).to eq([word_list])
    end
  end

  describe "GET #show" do
    it "assigns the requested word_list as @word_list" do
      word_list = WordList.create! valid_attributes
      get :show, {:id => word_list.to_param}, valid_session
      expect(assigns(:word_list)).to eq(word_list)
    end
  end

  describe "GET #new" do
    it "assigns a new word_list as @word_list" do
      get :new, {}, valid_session
      expect(assigns(:word_list)).to be_a_new(WordList)
    end
  end

  describe "GET #edit" do
    it "assigns the requested word_list as @word_list" do
      word_list = WordList.create! valid_attributes
      get :edit, {:id => word_list.to_param}, valid_session
      expect(assigns(:word_list)).to eq(word_list)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new WordList" do
        expect {
          post :create, {:word_list => valid_attributes}, valid_session
        }.to change(WordList, :count).by(1)
      end

      it "assigns a newly created word_list as @word_list" do
        post :create, {:word_list => valid_attributes}, valid_session
        expect(assigns(:word_list)).to be_a(WordList)
        expect(assigns(:word_list)).to be_persisted
      end

      it "redirects to the created word_list" do
        post :create, {:word_list => valid_attributes}, valid_session
        expect(response).to redirect_to(WordList.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved word_list as @word_list" do
        post :create, {:word_list => invalid_attributes}, valid_session
        expect(assigns(:word_list)).to be_a_new(WordList)
      end

      it "re-renders the 'new' template" do
        post :create, {:word_list => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested word_list" do
        word_list = WordList.create! valid_attributes
        put :update, {:id => word_list.to_param, :word_list => new_attributes}, valid_session
        word_list.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested word_list as @word_list" do
        word_list = WordList.create! valid_attributes
        put :update, {:id => word_list.to_param, :word_list => valid_attributes}, valid_session
        expect(assigns(:word_list)).to eq(word_list)
      end

      it "redirects to the word_list" do
        word_list = WordList.create! valid_attributes
        put :update, {:id => word_list.to_param, :word_list => valid_attributes}, valid_session
        expect(response).to redirect_to(word_list)
      end
    end

    context "with invalid params" do
      it "assigns the word_list as @word_list" do
        word_list = WordList.create! valid_attributes
        put :update, {:id => word_list.to_param, :word_list => invalid_attributes}, valid_session
        expect(assigns(:word_list)).to eq(word_list)
      end

      it "re-renders the 'edit' template" do
        word_list = WordList.create! valid_attributes
        put :update, {:id => word_list.to_param, :word_list => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested word_list" do
      word_list = WordList.create! valid_attributes
      expect {
        delete :destroy, {:id => word_list.to_param}, valid_session
      }.to change(WordList, :count).by(-1)
    end

    it "redirects to the word_lists list" do
      word_list = WordList.create! valid_attributes
      delete :destroy, {:id => word_list.to_param}, valid_session
      expect(response).to redirect_to(word_lists_url)
    end
  end

end
